name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#    - name: Set up Git LFS
#      run: |
#        git lfs install
#        git lfs pull

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"

#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt

#    - name: Prepare environment
#      run: |
#        python src/train_model.py

#    - name: Commit and push changes
#      run: |
#        git config --global user.email "github-actions[bot]@users.noreply.github.com"
#        git config --global user.name "github-actions[bot]"
#        if [ -n "$(git status --porcelain=data/processed/model.pkl)" ] || [ -n "$(git status --porcelain=data/processed/preprocessor.pkl)" ]; then
#          git add data/processed/model.pkl data/processed/preprocessor.pkl data/processed/global_importance.pkl data/processed/best_threshold.txt
#          git commit -m "Mise à jour preprocessor, model, best_threshold et global_importance [CI]"
#          git push
#        else
#          echo "preprocessor.pkl et model.pkl inchangés."
#        fi

#    - name: Delete hooks
#      run: |
#        if [ -f .git/hooks/pre-push ]; then
#          rm .git/hooks/pre-push
#          git commit -m "Suppression heroku hooks [CI]" --allow-empty
#          git push
#        else
#          echo "Aucun pre-push hook à supprimer."
#        fi

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name:  ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
     
#    - name: Run tests
#      run: python -m unittest discover -s tests
